[tool.poetry]
name = "spice-ev-simulator"
version = "0.1.0"
description = ""
authors = ["Ryan Popa"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.35.0"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
